version: '2'
services:

  db:
    image: "postgres:11"
    container_name: "users-db"
    restart: "unless-stopped"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=users
    ports:
      - "54321:5432"
    volumes:
      - ./postgres-datavolume:/var/lib/postgresql/data

